VAC!T/Controllers/FileUploadController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using VAC_T.Business;
using VAC_T.DAL.Exceptions;
using VAC_T.Models;

namespace VAC_T.Controllers
{
    public class FileUploadController : Controller
    {
        private UserManager<VAC_TUser> _userManager;
        private readonly FileUploadService _service;

        public FileUploadController(UserManager<VAC_TUser> userManager, FileUploadService service)
        {
            _userManager = userManager;
            _service = service;
        }

        public async Task<IActionResult> EditProfilePicture(string id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return base.NotFound($"Unable to load user with ID '{id}'.");
            }
            if (user.Id != id)
            {
                return base.Unauthorized("Kan profielfoto niet updaten");
            }
            return View(new ProfilePictureModel() { Id = id, ProfilePicture = user.ProfilePicture });
        }


        [HttpPost]
        public async Task<IActionResult> UploadProfilePicture(string id, IFormFile FormFile)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return base.NotFound($"Unable to load user with ID '{id}'.");
            }
            if (user.Id != id)
            {
                return base.Unauthorized("Kan profielfoto niet updaten");
            }

            if (FormFile == null)
            {
                return View("EditProfilePicture", new ProfilePictureModel() { Id = id, ProfilePicture = user.ProfilePicture });
            }
            try
            {
                await _service.UploadProfilePictureAsync(user, FormFile);
            }
            catch (InternalServerException)
            {
                return Problem("Database not connected");
            }
            return Redirect("/Identity/Account/Manage");
        }

        public async Task<IActionResult> EditCV(string id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return base.NotFound($"Unable to load user with ID '{id}'.");
            }
            if (user.Id != id)
            {
                return base.Unauthorized("Kan CV niet updaten");
            }
            return View(new CVModel() { Id = id, CV = user.CV });
        }

        [HttpPost]
        public async Task<IActionResult> UploadCV(string id, IFormFile FormFile)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return base.NotFound($"Unable to load user with ID '{id}'.");
            }
            if (user.Id != id)
            {
                return base.Unauthorized("Kan CV niet updaten");
            }

            if (FormFile == null)
            {
                return View("EditCV", new CVModel() { Id = id, CV = user.CV });
            }
            try
            {
                var result = await _service.UploadCVAsync(user, FormFile);
                if (result == false)
                {
                    ViewData["Message"] = "Je kan alleen een pdf uploaden";
                    return View("EditCV", new CVModel() { Id = id, CV = user.CV });
                } else
                {
                    ViewData["Message"] = null;
                }
            }
            catch (InternalServerException)
            {
                return Problem("Database not connected");
            }
            return Redirect("/Identity/Account/Manage");
        }

        [HttpGet]
        public IActionResult GetCV(string cv)
        {
            string filePath = "~/" + cv;
            string fileName = Path.GetFileName(filePath);
            Response.Headers.Add("Content-Disposition", $"inline; filename={fileName}");
            return File(filePath, "application/pdf");
        }

        public IActionResult CreateJobOfferLogoURL()
        {
            return View(new JobOfferLogoURLModel());
        }

        public async Task<IActionResult> UploadJobOfferLogoURL(string LanguageName, IFormFile FormFile)
        {
            if (!(User.IsInRole("ROLE_EMPLOYER") || User.IsInRole("ROLE_ADMIN")))
            {
                return base.Unauthorized("Kan geen Software Logo uploaden");
            }

            if (FormFile == null)
            {
                return View("CreateJobOfferLogoURL", new JobOfferLogoURLModel());
            }
            try
            {
                await _service.UploadJobOfferLogoURLAsync(LanguageName, FormFile);
            }
            catch (InternalServerException)
            {
                return Problem("Database not connected");
            }
            if (User.IsInRole("ROLE_ADMIN"))
            {
                return Redirect("/JobOffers/Index");
            }
            return Redirect("/JobOffers/Create");
        }

        public async Task<IActionResult> EditCompanyLogo(int id)
        {
            try
            {
                var company = await _service.GetCompanyByIdAsync(id);
                var user = await _userManager.GetUserAsync(User);
                if (company == null)
                {
                    return base.NotFound($"Unable to load company with ID '{id}'.");
                }
                if (company.User != user && !User.IsInRole("ROLE_ADMIN") || !User.IsInRole("ROLE_ADMIN"))
                {
                    return base.Unauthorized("Kan Bedrijf Logo niet updaten");
                }
                return View(new CompanyLogoModel() { Id = company.Id, LogoURL = company.LogoURL });
            }
            catch (InternalServerException)
            {
                return Problem("Database not connected");
            }
        }

        public async Task<IActionResult> UploadCompanyLogo(int id, IFormFile FormFile)
        {
            try
            {
                var company = await _service.GetCompanyByIdAsync(id);
                var user = await _userManager.GetUserAsync(User);
                if (company == null)
                {
                    return base.NotFound($"Unable to load company with ID '{id}'.");
                }
                if (company.User != user && !User.IsInRole("ROLE_ADMIN") || !User.IsInRole("ROLE_ADMIN"))
                {
                    return base.Unauthorized("Kan Bedrijf Logo niet uploaden");
                }

                if (FormFile == null)
                {
                    return View("EditCompanyLogo", new CompanyLogoModel() { Id = company.Id, LogoURL = company.LogoURL });
                }
                await _service.UploadCompanyLogoAsync(company, FormFile);

                if (User.IsInRole("ROLE_ADMIN"))
                {
                    return Redirect("/Companies/Index");
                }
                return Redirect("/Companies/Details/" + company.Id);
            }
            catch (InternalServerException)
            {
                return Problem("Database not connected");
            }
        }

        public string TrimQuotes(string text)
        {
            return text.Replace("\"", "").Trim();
        }
    }
}

VAC!T/Controllers/JobOffersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using VAC_T.Business;
using VAC_T.DAL.Exceptions;
using VAC_T.Models;

namespace VAC_T.Controllers
{
    public class JobOffersController : Controller
    {
        private readonly JobOfferService _service;

        public JobOffersController(JobOfferService service)
        {
            _service = service;
        }

        // GET: JobOffers
        public async Task<IActionResult> Index()
        {
            try
            {
                var jobOffers = await _service.GetJobOffersAsync(User);
                return View(jobOffers);
            }
            catch (InternalServerException)
            {
                return Problem("Entity set 'ApplicationDbContext.JobOffer' is null.");
            }
        }

        // GET: JobOffers/Details/5
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var jobOffer = await _service.GetJobOfferAsync(id, User);
                if (jobOffer == null)
                {
                    return NotFound();
                }
                return View(jobOffer);
            }
            catch (InternalServerException)
            {
                return Problem("Entity set 'ApplicationDbContext.JobOffer' is null.");
            }
        }

        // GET: JobOffers/Create
        public async Task<IActionResult> Create()
        {
            if (!User.IsInRole("ROLE_EMPLOYER"))
            {
                return Unauthorized("Not the correct roles.");
            }
            var jobOffer = new JobOffer();
            var company = await _service.GetCompanyForJobOfferAsync(User);
            jobOffer.CompanyId = company.Id;
            jobOffer.Residence = company.Residence;
            return View(jobOffer);
        }

        // POST: JobOffers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Description,LogoURL,Level,CompanyId,Residence")] JobOffer jobOffer)
        {
            if (!User.IsInRole("ROLE_EMPLOYER"))
            {
                return Unauthorized("Not the correct roles.");
            }
            ModelState.Remove("Company");
            if (ModelState.IsValid)
            {
                try
                {
                    jobOffer = await _service.CreateJobOfferAsync(jobOffer, User);
                    return RedirectToAction(nameof(Index));
                }
                catch (InternalServerException)
                {
                    return Problem("Entity set 'ApplicationDbContext.JobOffer' is null.");
                }
            }
            return View(jobOffer);
        }

        // GET: JobOffers/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (!(User.IsInRole("ROLE_ADMIN") || User.IsInRole("ROLE_EMPLOYER")))
            {
                return Unauthorized("Not the correct roles.");
            }
            try
            {
                var jobOffer = await _service.GetJobOfferAsync(id, User);
                if (jobOffer == null)
                {
                    return NotFound();
                }
                return View(jobOffer);
            }
            catch (InternalServerException)
            {
                return Problem("Entity set 'ApplicationDbContext.JobOffer' is null.");
            }
        }

        // POST: JobOffers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,LogoURL,Level,Created,Residence,CompanyId,Company")] JobOffer jobOffer)
        {
            if (!(User.IsInRole("ROLE_ADMIN") || User.IsInRole("ROLE_EMPLOYER")))
            {
                return Unauthorized("Not the correct roles.");
            }
            if (id != jobOffer.Id)
            {
                return NotFound();
            }
            ModelState.Remove("Company");
            if (ModelState.IsValid)
            {
                try
                {
                    if (!await _service.DoesJobOfferExistsAsync(id))
                    {
                        return NotFound();
                    }
                    await _service.UpdateJobOfferAsync(jobOffer);
                    return RedirectToAction("Details", new { id });
                }
                catch (InternalServerException)
                {
                    return Problem("Entity set 'ApplicationDbContext.JobOffer' is null.");
                }
            }
            return View(jobOffer);
        }

        // GET: JobOffers/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (!(User.IsInRole("ROLE_ADMIN") || User.IsInRole("ROLE_EMPLOYER")))
            {
                return Unauthorized("Not the correct roles.");
            }
            try
            {
                var jobOffer = await _service.GetJobOfferAsync(id, User);
                if (jobOffer == null)
                {
                    return NotFound();
                }

                return View(jobOffer);
            }
            catch (InternalServerException)
            {
                return Problem("Entity set 'ApplicationDbContext.JobOffer' is null.");
            }
        }

        // POST: JobOffers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (!(User.IsInRole("ROLE_ADMIN") || User.IsInRole("ROLE_EMPLOYER")))
            {
                return Unauthorized("Not the correct roles.");
            }
            try
            {
                await _service.DeleteJobOfferAsync(id);
                return RedirectToAction(nameof(Index));
            }
            catch (InternalServerException)
            {
                return Problem("Entity set 'ApplicationDbContext.JobOffer' is null.");
            }
        }

        public async Task<IActionResult> ChangeJobOfferStatus(int id)
        {
            if (!(User.IsInRole("ROLE_ADMIN") || User.IsInRole("ROLE_EMPLOYER")))
            {
                return Unauthorized("Not the correct roles.");
            }
            try
            {
                await _service.ChangeJobOfferStatusAsync(id);
                return RedirectToAction("Edit", new { id });
            }
            catch (InternalServerException)
            {
                return Problem("Entity set 'ApplicationDbContext.JobOffer' is null.");
            }
        }

        public async Task<IActionResult> SelectQuestionsForJobOffer(int id) //jobOffer Id
        {
            if (!(User.IsInRole("ROLE_ADMIN") || User.IsInRole("ROLE_EMPLOYER")))
            {
                return Unauthorized("Unauthorized");
            }
            try
            {
                var jobOffer = await _service.GetJobOfferWQuestionsAsync(id);
                if (jobOffer == null)
                {
                    return NotFound();
                }
                var questions = await _service.GetQuestionsForCompanyAsync(jobOffer.CompanyId);
                if (questions == null)
                {
                    return NotFound("No questions available to select from");
                }
                var selectList = new SelectList(questions, "Id", "QuestionText", jobOffer.Questions);
                ViewData["Questions"] = selectList;
                var viewModel = new SelectQuestionForJobOfferModel() { Id = id, SelectedQuestionIds = jobOffer.Questions.Select(j => j.Id).ToArray(), CompanyId = jobOffer.CompanyId};
                return View(viewModel);
            }
            catch (InternalServerException)
            {
                return Problem("Entity set 'ApplicationDbContext.JobOffer' is null.");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SelectQuestionsForJobOffer(int id, SelectQuestionForJobOfferModel selectedQuestions) //jobOffer Id
        {
            if (!(User.IsInRole("ROLE_ADMIN") || User.IsInRole("ROLE_EMPLOYER")))
            {
                return Unauthorized("Unauthorized");
            }
            if (id != selectedQuestions.Id)
            {
                return NotFound();
            }
            try
            {
                if (ModelState.IsValid)
                {
                    if (!await _service.DoesJobOfferExistsAsync(id))
                    {
                        return NotFound();
                    }
                    //var jobOffer = await _service.GetJobOfferWQuestionsAsync(id);
                    await _service.SelectJobOfferQuestionsAsync(id, selectedQuestions.SelectedQuestionIds);
                    return RedirectToAction("Details", new { id });
                }
                var questions = await _service.GetQuestionsForCompanyAsync(selectedQuestions.CompanyId);
                if (questions == null)
                {
                    return NotFound("No questions available to select from");
                }
                ViewData["Questions"] = new SelectList(questions, "Id", "QuestionText");
                return View(selectedQuestions);
            }
            catch (InternalServerException)
            {
                return Problem("Entity set 'ApplicationDbContext.JobOffer' is null.");
            }
        }

    }
}

VAC!T/Views/Companies/Create.cshtml
@model VAC_T.Models.Company

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-orange">
    <h1>Bedrijf Toevoegen</h1>
</div>

<hr />
<div class="row">
    <div class="col-md-7">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>
            <input type="hidden" asp-for="LogoURL" />
            <div class="form-floating mb-3 text-orange">
                <input asp-for="Name" class="form-control" />
                <label asp-for="Name" class="control-label"></label>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3 text-orange">
                <textarea asp-for="Description" class="form-control"></textarea>
                <label asp-for="Description" class="control-label"></label>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3 text-orange">
                <input asp-for="WebsiteURL" class="form-control" />
                <label asp-for="WebsiteURL" class="control-label"></label>
                <span asp-validation-for="WebsiteURL" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3 text-orange">
                <input asp-for="Address" class="form-control" />
                <label asp-for="Address" class="control-label"></label>
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3 text-orange">
                <input asp-for="Postcode" class="form-control" />
                <label asp-for="Postcode" class="control-label"></label>
                <span asp-validation-for="Postcode" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3 text-orange">
                <input asp-for="Residence" class="form-control" />
                <label asp-for="Residence" class="control-label"></label>
                <span asp-validation-for="Residence" class="text-danger"></span>
            </div>
            <div class="form-floating padding-top-5">
                <input type="submit" value="Volgende" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Terug</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VAC!T/Views/Companies/Delete.cshtml
@model VAC_T.Models.Company

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Weet je zeker dat je dit wilt verwijderen?</h3>
<div>
    <h4>Bedrijf</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LogoURL)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LogoURL)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WebsiteURL)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WebsiteURL)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
    </dl>
    
    <form asp-action="DeleteConfirmed">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">
            <input type="button" value="Terug naar bedrijven" class="btn btn-primary" />
        </a>
    </form>
</div>

VAC!T/Views/Companies/Details.cshtml
@model VAC_T.Models.Company

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="row align-items-center">
        <div class="Company-logo col-2">
            <img class="rounded-circle" src="@Url.Content(("~/" + Model.LogoURL))" width="100%" alt="Logo afbeelding" />
        </div>
        <div class="userdetails-title col-10 d-flex text-orange ">
            <h1>Details @Model.Name</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-2"></div>
        <div class="col-10">
            <dl class="col-8 row">
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.WebsiteURL)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.WebsiteURL)
                </dd>
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.Address)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Address)
                </dd>
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.Postcode)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Postcode)
                </dd>
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.Residence)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Residence)
                </dd>
            </dl>
            <div class="company-description-title text-orange col-12">
                <h4>@Html.DisplayNameFor(model => model.Description)</h4>
            </div>
            <div class="company-description col-12">
                <p>@Html.DisplayFor(model => model.Description)</p>
            </div>
        </div>
    </div>
    @if (User.IsInRole("ROLE_EMPLOYER") || User.IsInRole("ROLE_ADMIN"))
    {
        <div class="row">
            <div class="col-2"></div>
            <div class="col-10">
                <a class="companydetails-edit-button text-decoration-none text-orange bottom-50" asp-action="Edit" asp-route-id="@Model?.Id">
                    <h4 class="padding-top-5">Edit</h4>
                </a>
            </div>
        </div>
    }
    <div class="row">
        <div class="col-2">
        </div>
        <div class="col-10">
            <div class="company-details-joboffer white-space-pre-wrap d-inline-flex">
                <h5>Vacatures van</h5>
                <div class="jobOffer-details-company-name text-orange d-inline-flex">
                    <h5> @Model.Name</h5>
                </div>
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.JobOffers.FirstOrDefault().Created)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.JobOffers.FirstOrDefault().Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.JobOffers.FirstOrDefault().Level)
                        </th>
                        @if (User.IsInRole("ROLE_EMPLOYER") || User.IsInRole("ROLE_ADMIN"))
                        {
                            <th>
                                Opties
                            </th>
                        }
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.JobOffers)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Created)
                            </td>
                            <td>
                                <a class="text-decoration-none text-orange" asp-controller="JobOffers" asp-action="Details" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.Name)</a>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Level)
                            </td>
                            @if (User.IsInRole("ROLE_EMPLOYER") || User.IsInRole("ROLE_ADMIN"))
                            {
                                <td>
                                    <a class="text-decoration-none text-orange" asp-controller="JobOffers" asp-action="Edit" asp-route-id="@item.Id">Edit</a> | 
                                    <a class="text-decoration-none text-orange" asp-controller="JobOffers" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                </td>
                            }
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

VAC!T/Views/Companies/Edit.cshtml
@model VAC_T.Models.Company

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="text-orange">
    <h1>Edit</h1>

    <h4>Bedrijf</h4>
</div>
<hr />
<div class="row">
    <div class="col-md-7">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="User" />
            <input type="hidden" asp-for="LogoURL" />
            <div class="form-floating mb-3 text-orange">
                <input asp-for="Name" class="form-control" />
                <label asp-for="Name" class="control-label"></label>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3 text-orange">
                <textarea asp-for="Description" class="form-control" rows="10"></textarea>
                <label asp-for="Description" class="control-label"></label>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3 text-orange">
                <input asp-for="WebsiteURL" class="form-control" rows="10"/>
                <label asp-for="WebsiteURL" class="control-label"></label>
                <span asp-validation-for="WebsiteURL" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3 text-orange">
                <input asp-for="Address" class="form-control" />
                <label asp-for="Address" class="control-label"></label>
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3 text-orange">
                <input asp-for="Postcode" class="form-control" />
                <label asp-for="Postcode" class="control-label"></label>
                <span asp-validation-for="Postcode" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3 text-orange">
                <input asp-for="Residence" class="form-control" />
                <label asp-for="Residence" class="control-label"></label>
                <span asp-validation-for="Residence" class="text-danger"></span>
            </div>
            <div class="form-floating">
                <input type="submit" value="Opslaan" class="btn btn-primary" />
            </div>
        </form>
    </div>
    <div class="Opload-new-LogoURL-JobOffer padding-top-5">
        <a class="navbar-brand" asp-area="" asp-controller="FileUpload" asp-action="EditCompanyLogo" asp-route-id="@Model.Id">
            <input type="button" value="Logo veranderen" class="btn btn-primary" />
        </a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VAC!T/Views/Companies/Index.cshtml
@model IEnumerable<VAC_T.Models.Company>

@{
    ViewData["Title"] = "Bedrijven";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="text-orange">
<h1>Bedrijven</h1>
</div>

<p>
    <a class="text-decoration-none text-orange" asp-action="Create">Bedrijf toevoegen</a>
</p>

<form class="container-fluid" asp-action="Index" method="get">
    <div class="form-action row align-items-center">
        <p>
            <div class="col-3">
                Bedrijf: <input type="text" class="form-control" name="searchName" value="@ViewData["searchName"]" />
            </div>
            <div class="col-3">
                <input type="submit" value="Filter" class="btn btn-primary" />
                <a asp-action="index">
                    <input type="button" value="Clear" class="btn btn-primary" /></a>
            </div>
        </p>
        <hr />
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                Opties
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a class="text-decoration-none text-orange"  asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a class="text-decoration-none text-orange"  asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a class="text-decoration-none text-orange" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>