VAC!T/Controllers/FileUploadController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using VAC_T.Business;
using VAC_T.DAL.Exceptions;
using VAC_T.Models;

namespace VAC_T.Controllers
{
    public class FileUploadController : Controller
    {
        private UserManager<VAC_TUser> _userManager;
        private readonly FileUploadService _service;

        public FileUploadController(UserManager<VAC_TUser> userManager, FileUploadService service)
        {
            _userManager = userManager;
            _service = service;
        }

        public async Task<IActionResult> EditProfilePicture(string id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return base.NotFound($"Unable to load user with ID '{id}'.");
            }
            if (user.Id != id)
            {
                return base.Unauthorized("Kan profielfoto niet updaten");
            }
            return View(new ProfilePictureModel() { Id = id, ProfilePicture = user.ProfilePicture });
        }


        [HttpPost]
        public async Task<IActionResult> UploadProfilePicture(string id, IFormFile FormFile)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return base.NotFound($"Unable to load user with ID '{id}'.");
            }
            if (user.Id != id)
            {
                return base.Unauthorized("Kan profielfoto niet updaten");
            }

            if (FormFile == null)
            {
                return View("EditProfilePicture", new ProfilePictureModel() { Id = id, ProfilePicture = user.ProfilePicture });
            }
            try
            {
                await _service.UploadProfilePictureAsync(user, FormFile);
            }
            catch (InternalServerException)
            {
                return Problem("Database not connected");
            }
            return Redirect("/Identity/Account/Manage");
        }

        public async Task<IActionResult> EditCV(string id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return base.NotFound($"Unable to load user with ID '{id}'.");
            }
            if (user.Id != id)
            {
                return base.Unauthorized("Kan CV niet updaten");
            }
            return View(new CVModel() { Id = id, CV = user.CV });
        }

        [HttpPost]
        public async Task<IActionResult> UploadCV(string id, IFormFile FormFile)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return base.NotFound($"Unable to load user with ID '{id}'.");
            }
            if (user.Id != id)
            {
                return base.Unauthorized("Kan CV niet updaten");
            }

            if (FormFile == null)
            {
                return View("EditCV", new CVModel() { Id = id, CV = user.CV });
            }
            try
            {
                var result = await _service.UploadCVAsync(user, FormFile);
                if (result == false)
                {
                    ViewData["Message"] = "Je kan alleen een pdf uploaden";
                    return View("EditCV", new CVModel() { Id = id, CV = user.CV });
                } else
                {
                    ViewData["Message"] = null;
                }
            }
            catch (InternalServerException)
            {
                return Problem("Database not connected");
            }
            return Redirect("/Identity/Account/Manage");
        }

        [HttpGet]
        public IActionResult GetCV(string cv)
        {
            string filePath = "~/" + cv;
            string fileName = Path.GetFileName(filePath);
            Response.Headers.Add("Content-Disposition", $"inline; filename={fileName}");
            return File(filePath, "application/pdf");
        }

        public IActionResult CreateJobOfferLogoURL()
        {
            return View(new JobOfferLogoURLModel());
        }

        public async Task<IActionResult> UploadJobOfferLogoURL(string LanguageName, IFormFile FormFile)
        {
            if (!(User.IsInRole("ROLE_EMPLOYER") || User.IsInRole("ROLE_ADMIN")))
            {
                return base.Unauthorized("Kan geen Software Logo uploaden");
            }

            if (FormFile == null)
            {
                return View("CreateJobOfferLogoURL", new JobOfferLogoURLModel());
            }
            try
            {
                await _service.UploadJobOfferLogoURLAsync(LanguageName, FormFile);
            }
            catch (InternalServerException)
            {
                return Problem("Database not connected");
            }
            if (User.IsInRole("ROLE_ADMIN"))
            {
                return Redirect("/JobOffers/Index");
            }
            return Redirect("/JobOffers/Create");
        }

        public async Task<IActionResult> EditCompanyLogo(int id)
        {
            try
            {
                var company = await _service.GetCompanyByIdAsync(id);
                var user = await _userManager.GetUserAsync(User);
                if (company == null)
                {
                    return base.NotFound($"Unable to load company with ID '{id}'.");
                }
                if (company.User != user && !User.IsInRole("ROLE_ADMIN") || !User.IsInRole("ROLE_ADMIN"))
                {
                    return base.Unauthorized("Kan Bedrijf Logo niet updaten");
                }
                return View(new CompanyLogoModel() { Id = company.Id, LogoURL = company.LogoURL });
            }
            catch (InternalServerException)
            {
                return Problem("Database not connected");
            }
        }

        public async Task<IActionResult> UploadCompanyLogo(int id, IFormFile FormFile)
        {
            try
            {
                var company = await _service.GetCompanyByIdAsync(id);
                var user = await _userManager.GetUserAsync(User);
                if (company == null)
                {
                    return base.NotFound($"Unable to load company with ID '{id}'.");
                }
                if (company.User != user && !User.IsInRole("ROLE_ADMIN") || !User.IsInRole("ROLE_ADMIN"))
                {
                    return base.Unauthorized("Kan Bedrijf Logo niet uploaden");
                }

                if (FormFile == null)
                {
                    return View("EditCompanyLogo", new CompanyLogoModel() { Id = company.Id, LogoURL = company.LogoURL });
                }
                await _service.UploadCompanyLogoAsync(company, FormFile);

                if (User.IsInRole("ROLE_ADMIN"))
                {
                    return Redirect("/Companies/Index");
                }
                return Redirect("/Companies/Details/" + company.Id);
            }
            catch (InternalServerException)
            {
                return Problem("Database not connected");
            }
        }

        public string TrimQuotes(string text)
        {
            return text.Replace("\"", "").Trim();
        }
    }
}

VAC!T/Controllers/UserDetailsController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using VAC_T.DAL.Exceptions;
using VAC_T.Business;
using VAC_T.Models;

namespace VAC_T.Controllers
{
    public class UserDetailsController : Controller
    {
        private UserManager<VAC_TUser> _userManager;
        private UserDetailsService _service;

        public UserDetailsController(UserManager<VAC_TUser> userManager, UserDetailsService service)
        {
            _userManager = userManager;
            _service = service;
        }

        public async Task<IActionResult> Index(string searchEmail, string searchName)
        {
            if (!User.IsInRole("ROLE_ADMIN"))
            {
                return Unauthorized("Not the correct roles.");
            }

            ViewData["searchEmail"] = searchEmail;
            ViewData["searchName"] = searchName;

            try
            {
                var users = await _service.GetUsersAsync(searchName, searchEmail);
                return View(users);

            }
            catch (InternalServerException)
            {
                return Problem("Entity set 'ApplicationDbContext.Users' is null.");
            }
        }

        // GET: UserDetailsModels/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (!(User.IsInRole("ROLE_ADMIN") || User.IsInRole("ROLE_EMPLOYER")))
            {
                return Unauthorized("Not the correct roles.");
            }

            try
            {
                var user = await _service.GetUserDetailsAsync(id);
                if (user == null)
                {
                    return NotFound("User not found.");
                }

                return View(new UserDetailsModel()
                {
                    Id = user.Id,
                    Name = user.Name,
                    PhoneNumber = user.PhoneNumber,
                    Email = user.Email,
                    BirthDate = user.BirthDate,
                    Address = user.Address,
                    Postcode = user.Postcode,
                    Residence = user.Residence,
                    ProfilePicture = user.ProfilePicture,
                    Motivation = user.Motivation,
                    CV = user.CV,
                    Role = (await _userManager.GetRolesAsync(user)).First(),
                });
            }
            catch (InternalServerException)
            {
                return Problem("Entity set 'ApplicationDbContext.Users' is null.");
            }
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (!User.IsInRole("ROLE_ADMIN"))
            {
                return Unauthorized("Not the correct roles.");
            }
            try
            {
                var user = await _service.GetUserDetailsAsync(id);
                if (user == null)
                {
                    return NotFound();
                }

                return View(user);
            }
            catch (InternalServerException)
            {
                return Problem("Entity set 'ApplicationDbContext.Users' is null.");
            }
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (!User.IsInRole("ROLE_ADMIN"))
            {
                return Unauthorized("Not the correct roles.");
            }
            try
            {
                await _service.DeleteUserAsync(id);
                return RedirectToAction(nameof(Index));
            }
            catch (InternalServerException)
            {
                return Problem("Entity set 'ApplicationDbContext.Users' is null.");
            }
        }
    }
}

VAC!T/Views/UserDetails/Delete.cshtml
@model VAC_T.Models.VAC_TUser
@using Microsoft.AspNetCore.Identity;
@inject UserManager<VAC_TUser> UserManager
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string Role = (await UserManager.GetRolesAsync(Model)).First();
}

<h1>Delete</h1>

<h3>Weet je zeker dat je deze user wil verwijderen?</h3>
<div>
    <hr />
    <dl class="col-8 row">
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-3">
            Telefoonnummer
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Postcode)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.Postcode)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Residence)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.Residence)
        </dd>
        <dt class="col-sm-3">
            Role
        </dt>
        <dd class="col-sm-9">
            @Role
        </dd>
    </dl>
    @if (Role == "ROLE_CANDIDATE")
    {
        <div class="userdetails-motivation-title text-orange col-12">
            <h4>@Html.DisplayNameFor(model => model.Motivation)</h4>
        </div>
        <div class="userdetails-motivation col-12">
            <p>@Html.DisplayFor(model => model.Motivation)</p>
        </div>
        <div class="userdetails-CV-title text-orange col-12">
            <h4>@Html.DisplayNameFor(model => model.CV)</h4>
        </div>
        <div class="userdetails-CV col-12">
            <img class="rounded-circle" src=@Url.Content("~/" + Model.CV) height="150" width="150" alt="CV bestand" />
        </div>
    }

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">
            <input type="button" value="Terug naar users" class="btn btn-primary" />
        </a>
    </form>
</div>

VAC!T/Views/UserDetails/Details.cshtml
@model VAC_T.Models.UserDetailsModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="container-fluid">
    <div class="row align-items-center">
        <div class="profile-picture col-2">
            <img class="rounded-circle" src="@Url.Content(("~/" + Model.ProfilePicture))" width="100%" alt="Profiel afbeelding" />
        </div>
        <div class="userdetails-title col-10 d-flex text-orange ">
            <h1>Details @Model.Name</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-2"></div>
        <div class="col-10">
            <dl class="col-8 row">
                <dt class = "col-sm-3">
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd class = "col-sm-9">
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt class = "col-sm-3">
                    @Html.DisplayNameFor(model => model.Email)
                </dt>
                <dd class = "col-sm-9">
                    @Html.DisplayFor(model => model.Email)
                </dd>
                <dt class = "col-sm-3">
                    @Html.DisplayNameFor(model => model.PhoneNumber)
                </dt>
                <dd class = "col-sm-9">
                    @Html.DisplayFor(model => model.PhoneNumber)
                </dd>
                <dt class = "col-sm-3">
                    @Html.DisplayNameFor(model => model.BirthDate)
                </dt>
                <dd class = "col-sm-9">
                    @Html.DisplayFor(model => model.BirthDate)
                </dd>
                <dt class = "col-sm-3">
                    @Html.DisplayNameFor(model => model.Address)
                </dt>
                <dd class = "col-sm-9">
                    @Html.DisplayFor(model => model.Address)
                </dd>
                <dt class = "col-sm-3">
                    @Html.DisplayNameFor(model => model.Postcode)
                </dt>
                <dd class = "col-sm-9">
                    @Html.DisplayFor(model => model.Postcode)
                </dd>
                <dt class = "col-sm-3">
                    @Html.DisplayNameFor(model => model.Residence)
                </dt>
                <dd class = "col-sm-9">
                    @Html.DisplayFor(model => model.Residence)
                </dd>
            </dl>
            @if (Model.Role == "ROLE_CANDIDATE")
            {
                <div class="userdetails-motivation-title text-orange col-12">
                    <h4>@Html.DisplayNameFor(model => model.Motivation)</h4>
                </div>
                <div class="userdetails-motivation col-12">
                    <p>@Html.DisplayFor(model => model.Motivation)</p>
                </div>
                <div class="userdetails-CV-title text-orange col-12">
                    <h4>@Html.DisplayNameFor(model => model.CV)</h4>
                </div>
                <div class="userdetails-CV col-12">
                    <img class="rounded-circle" src=@Url.Content("~/" + Model.CV) height="150" width="150" alt="CV bestand" />
                </div>
                @if (Model.CV != null)
                {
                <a class="text-decoration-none" asp-controller="FileUpload" asp-action="GetCV" asp-route-cv="@Model.CV">
                    <input type="button" value="Download/View CV" class="btn btn-primary" />
                </a>                  
                }
            }
        </div>
    </div>
</div>

VAC!T/Views/UserDetails/Index.cshtml
@model IEnumerable<VAC_T.Models.VAC_TUser>

@{
    ViewData["Title"] = "Users";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-orange">
<h1>Users</h1>
</div>

<form class="container-fluid" asp-action="Index" method="get">
    <div class="form-action row align-items-center">
        <p>
            <div class="col-3">
            Naam: <input type="text" class="form-control" name="searchName" value="@ViewData["searchName"]" />
            </div>
            <div class="col-3">
            Email: <input type="text" class="form-control" name="searchEmail" value="@ViewData["searchEmail"]" />
            </div>
            <div class="col-3">
                <input type="submit" value="Filter" class="btn btn-primary"/>
                <a asp-action="index">
                    <input type="button" value="Clear" class="btn btn-primary" /></a>
            </div>
        </p>
        <hr />
    </div>
</form>

<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    Opties
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        <a class="text-decoration-none text-orange" asp-controller="UserDetails" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a class="text-decoration-none text-orange" asp-controller="UserDetails" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>