VAC!T/Controllers/AnswersController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using VAC_T.Business;
using VAC_T.DAL.Exceptions;
using VAC_T.Models;
using CsvHelper;
using System.Text;
using System.Globalization;
using CsvHelper.Configuration;
using Microsoft.IdentityModel.Tokens;

namespace VAC_T.Controllers
{
    public class AnswersController : Controller
    {
        private readonly AnswerService _service;
        private readonly IMapper _mapper;
        private readonly SignInManager<VAC_TUser> _signInManager;
        public AnswersController(AnswerService service, IMapper mapper, SignInManager<VAC_TUser> signInManager)
        {
            _service = service;
            _mapper = mapper;
            _signInManager = signInManager;
        }

        // GET: Answers
        public async Task<IActionResult> Index()
        {
            if (!_signInManager.IsSignedIn(User))
            {
                return Unauthorized("Unauthorized, Need to be logged in");
            }
            try
            {
                if (User.IsInRole("ROLE_ADMIN"))
                {
                    ViewData["JobOffers"] = new SelectList(await _service.GetJobOffersAsync(), "Id", "Name");
                }
                var answers = await _service.GetAnswersAsync(User);
                return View(answers);
            }
            catch (InternalServerException)
            {
                return Problem("Entity set 'ApplicationDbContext.Answer' is null.");
            }
        }

        public async Task<IActionResult> DetailsPerJobOffer(int id, string userId) // jobOffer id
        {
            if (!_signInManager.IsSignedIn(User))
            {
                return Unauthorized("Unauthorized");
            }
            try
            {
                var answers = await _service.GetAnswersForJobOfferAsync(id, userId, User);
                if (answers.IsNullOrEmpty())
                {
                    return Unauthorized("Unauthorized, you are not allowed to view the details of this jobOffer or user");
                }
                var viewModel = _mapper.Map<List<AnswerViewModel>>(answers);
                foreach (var answer in viewModel)
                {
                    answer.DisplayAnswerText = _service.PrepareAnswerForDisplay(answer.AnswerText, answer.Question);
                }
                if (User.IsInRole("ROLE_ADMIN") || User.IsInRole("ROLE_CANDIDATE"))
                {
                    if (await _service.CheckUserSolicitatedAsync(id, userId))
                    {
                        ViewData["Solicitated"] = true;
                    } else
                    {
                        ViewData["Solicitated"] = null;
                    }
                }
                return View(viewModel);
            }
            catch (InternalServerException)
            {
                return Problem("Entity set 'ApplicationDbContext.Answer' is null.");
            }
        }

        // GET: Answers/Details/5
        //public async Task<IActionResult> Details(int id)
        //{
        //    try
        //    {
        //        var answer = await _service.GetAnswerAsync(id);
        //        if (answer == null)
        //        {
        //            return NotFound();
        //        }

        //        return View(answer);
        //    }
        //    catch (InternalServerException)
        //    {
        //        return Problem("Entity set 'ApplicationDbContext.Answer' is null.");
        //    }
        //}

        public async Task<IActionResult> AnswerQuestions(int id) // jobOffer id
        {
            if (!(User.IsInRole("ROLE_ADMIN") || User.IsInRole("ROLE_CANDIDATE")))
            {
                return Unauthorized("Unauthorized");
            }
            try
            {
                if (await _service.DoAnswersExistAsync(id, User))
                {
                    var user = await _service.GetUserAsync(User);
                    return RedirectToAction("DetailsPerJobOffer", new { id, userId = user.Id });
                    //var answers = await _service.GetUserAnswersForJobOfferAsync(id, User);
                    //return View("Edit", answers);
                }
                else
                {
                    return RedirectToAction("Create", new { id });
                    //var answers = await _service.PrepareUserAnswersForCreateAsync(id, User);
                    //if (answers == null)
                    //{
                    //    return NotFound("No questions are made yet");
                    //}
                    //return View("Create", answers);
                }
            }
            catch (InternalServerException)
            {
                return Problem("Entity set 'ApplicationDbContext.Answer' is null.");
            }
        }

        // GET: Answers/Create
        public async Task<IActionResult> Create(int id) // jobOffer id
        {
            if (!(User.IsInRole("ROLE_ADMIN") || User.IsInRole("ROLE_CANDIDATE")))
            {
                return Unauthorized("Unauthorized");
            }
            try
            {
                if (await _service.DoAnswersExistAsync(id, User))
                {
                    return BadRequest("You already answered the questions");
                }
                var answers = await _service.PrepareUserAnswersForCreateAsync(id, User);
                if (answers == null)
                {
                    return NotFound("No questions are made yet");
                }
                var viewModel = _mapper.Map<List<AnswerViewModel>>(answers);
                return View(viewModel.ToArray());
            }
            catch (InternalServerException)
            {
                return Problem("Entity set 'ApplicationDbContext.Answer' is null.");
            }
        }

        // POST: Answers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,QuestionId,JobOfferId,UserId,AnswerText,MultipleChoiceAnswers,Explanation")] AnswerViewModel[] answersViewModel)
        {
            if (!(User.IsInRole("ROLE_ADMIN") || User.IsInRole("ROLE_CANDIDATE")))
            {
                return Unauthorized("Unauthorized");
            }
            try
            {
                for (int i = 0; i < answersViewModel.Count(); i++)
                {
                    var question = await _service.GetQuestionAsync(answersViewModel[i].QuestionId);
                    if (question == null)
                    {
                        return BadRequest();
                    }
                    answersViewModel[i].Question = question;
                    ModelState.Remove($"[{i}].Question");
                    ModelState.Remove($"[{i}].JobOffer");
                    ModelState.Remove($"[{i}].User");
                    if (!(answersViewModel[i].Question.Type == "Meerkeuze" && answersViewModel[i].Question.MultipleOptions == true))
                    {
                        ModelState.Remove($"[{i}].MultipleChoiceAnswers");
                    }
                    else
                    {
                        ModelState.Remove($"[{i}].AnswerText");
                    }
                }
                if (ModelState.IsValid)
                {
                    //for (int i = 0; i < answersViewModel.Count(); i++)
                    //{
                    //    if (answersViewModel[i].Question.Type == "Meerkeuze" && answersViewModel[i].Question.MultipleOptions == true)
                    //    {
                    //        for (int s = 0; s < answersViewModel[i].MultipleChoiceAnswers.Count(); s++)
                    //        {
                    //            answersViewModel[i].AnswerText += answersViewModel[i].MultipleChoiceAnswers[s] + "_";
                    //        }
                    //        answersViewModel[i].AnswerText = answersViewModel[i].AnswerText.Trim('_');
                    //    }
                    //}
                    var answers = _mapper.Map<List<Answer>>(answersViewModel);
                    var createdAnswers = await _service.CreateAnswersAsync(answers);
                    return RedirectToAction(nameof(DetailsPerJobOffer), new { id = createdAnswers.First().JobOfferId, userId = createdAnswers.First().UserId });
                }
                return View(answersViewModel);
            }
            catch (InternalServerException)
            {
                return Problem("Entity set 'ApplicationDbContext.Answer' is null.");
            }
        }

        // GET: Answers/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (!(User.IsInRole("ROLE_ADMIN") || User.IsInRole("ROLE_CANDIDATE")))
            {
                return Unauthorized("Unauthorized");
            }
            try
            {
                var answer = await _service.GetAnswerAsync(id, User);
                if (answer == null)
                {
                    return NotFound();
                }
                var viewModel = _mapper.Map<AnswerViewModel>(answer);
                if (viewModel.Question.Type == "Meerkeuze" && viewModel.Question.MultipleOptions == true)
                {
                    viewModel.MultipleChoiceAnswers = viewModel.AnswerText.Split('_');
                }
                return View(viewModel);
            }
            catch (InternalServerException)
            {
                return Problem("Entity set 'ApplicationDbContext.Answer' is null.");
            }
        }

        // POST: Answers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.

VAC!T/Controllers/CompaniesController.cs
using Microsoft.AspNetCore.Mvc;
using VAC_T.Business;
using VAC_T.DAL.Exceptions;
using VAC_T.Models;

namespace VAC_T.Controllers
{
    public class CompaniesController : Controller
    {
        private CompanyService _service;

        public CompaniesController(CompanyService service)
        {
            _service = service;
        }

        // GET: Companies
        public async Task<IActionResult> Index(string? searchName)
        {
            if (!User.IsInRole("ROLE_ADMIN"))
            {
                return Unauthorized("Not the correct roles.");
            }
            ViewData["searchName"] = searchName;

            try {
                var companies = await _service.GetCompaniesAsync(searchName);

                return View(companies);

            } 
            catch (InternalServerException) 
            {
                return Problem("Entity set 'ApplicationDbContext.Company' is null.");
            }
        }

        // GET: Companies/Details/5
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var company = await _service.GetCompanyAsync(id, User);
                if (company == null)
                {
                    return NotFound();
                }

                return View(company);
            }
            catch (InternalServerException)
            {
                return Problem("Entity set 'ApplicationDbContext.Company' is null.");
            }
        }

        public async Task<IActionResult> DetailsForEmployer()
        {
            try
            {
                var company = await _service.GetCompanyForUserAsync(User);
                if (company == null)
                {
                    return NotFound();
                }

                return View("Details", company);
            }
            catch (InternalServerException)
            {
                return Problem("Entity set 'ApplicationDbContext.Company' is null.");
            }
        }

        // GET: Companies/Create
        public IActionResult Create()
        {
            if (!User.IsInRole("ROLE_ADMIN"))
            {
                return Unauthorized("Not the correct roles.");
            }
            var company = new Company();
            company.LogoURL = "assets/img/company/default.png";
            return View(company);
        }

        // POST: Companies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,LogoURL,WebsiteURL,Address,Postcode,Residence")] Company company)
        {
            if (!User.IsInRole("ROLE_ADMIN"))
            {
                return Unauthorized("Not the correct roles.");
            }
            if (ModelState.IsValid)
            {
                try { 
                    company = await _service.CreateCompanyWithUserAsync(company);

                    int id = company.Id;
                    return RedirectToAction("EditCompanyLogo", "FileUpload", new { id });
                }
                catch (InternalServerException)
                {
                    return Problem("Entity set 'ApplicationDbContext.Company' is null.");
                }

            }
            return View(company);
        }

        // GET: Companies/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (!(User.IsInRole("ROLE_ADMIN") || User.IsInRole("ROLE_EMPLOYER")))
            {
                return Unauthorized("Not the correct roles.");
            }
            try { 
                var company = await _service.GetCompanyAsync(id, User);
                if (company == null)
                {
                    return NotFound();
                }
                return View(company);
            }
            catch (InternalServerException)
            {
                return Problem("Entity set 'ApplicationDbContext.Company' is null.");
            }

        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,LogoURL,WebsiteURL,Address,Postcode,Residence")] Company company)
        {
            if (!(User.IsInRole("ROLE_ADMIN") || User.IsInRole("ROLE_EMPLOYER")))
            {
                return Unauthorized("Not the correct roles.");
            }
            if (id != company.Id)
            {
                return NotFound();
            }
            ModelState.Remove("User");
            if (ModelState.IsValid)
            {
                try
                {
                    if (!await _service.DoesCompanyExistsAsync(id))
                    {
                        return NotFound();
                    }
                    await _service.UpdateCompanyAsync(company);
                    return RedirectToAction(nameof(Details), new {id = company.Id});
                }
                catch (InternalServerException)
                {
                    return Problem("Entity set 'ApplicationDbContext.Company' is null.");
                }
            }
            return View(company);
        }

        // GET: Companies/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (!User.IsInRole("ROLE_ADMIN"))
            {
                return Unauthorized("Not the correct roles.");
            }
            try { 
                var company = await _service.GetCompanyAsync(id, User);
                if (company == null)
                {
                    return NotFound();
                }

                return View(company);
            }
            catch (InternalServerException)
            {
                return Problem("Entity set 'ApplicationDbContext.Company' is null.");
            }

        }

        // POST: Companies/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (!User.IsInRole("ROLE_ADMIN"))
            {
                return Unauthorized("Not the correct roles.");
            }
            try
            {
                await _service.DeleteCompanyAsync(id);
                return RedirectToAction(nameof(Index));
            }
            catch (InternalServerException)
            {
                return Problem("Entity set 'ApplicationDbContext.Company' is null.");
            }
        }
    }
}

VAC!T/Views/Solicitations/Create.cshtml
@model VAC_T.Models.Solicitation

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Solicitation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Selected" class="control-label"></label>
                <input asp-for="Selected" class="form-control" />
                <span asp-validation-for="Selected" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VAC!T/Views/Solicitations/Delete.cshtml
@model VAC_T.Models.Solicitation

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Solicitation</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Selected)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Selected)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

VAC!T/Views/Solicitations/Details.cshtml
@model VAC_T.Models.Solicitation

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Solicitation</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Selected)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Selected)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

VAC!T/Views/Solicitations/Edit.cshtml
@model VAC_T.Models.Solicitation

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Solicitation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Selected" class="control-label"></label>
                <input asp-for="Selected" class="form-control" />
                <span asp-validation-for="Selected" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VAC!T/Views/Solicitations/Index.cshtml
@model IEnumerable<VAC_T.Models.Solicitation>
@using Microsoft.AspNetCore.Identity;
@inject UserManager<VAC_TUser> UserManager
@inject RoleManager<IdentityRole> RoleManager
@inject SignInManager<VAC_TUser> SignInManager
@{
    ViewData["Title"] = "Mijn Sollicitaties";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@if (SignInManager.IsSignedIn(User))
{
    <div class="container-fluid">
        <div class="row align-items-center">
            <div class="Solicitation-profile-pic col-2">
                <img class="rounded-circle" src="@Url.Content("~/" + (await UserManager.GetUserAsync(User)).ProfilePicture)" width="100%" alt="Profiel afbeelding">
            </div>
            <div class="Solicitations-title col-10 text-orange d-flex">
                <h1>MIJN SOLLICITATIES</h1>
            </div>
        </div>
        
        <div class="row align-items-center">
            <div class="col-2"></div>
            <div class="form-action col-10">
                <form class="row align-items-center" asp-action="Index" method="get">
                    <p>
                        <div class="col-4">
                            Vacature: <input type="text" class="form-control" name="searchJobOffer" value="@ViewData["searchJobOffer"]" />
                        </div>
                        @if (User.IsInRole("ROLE_CANDIDATE") || User.IsInRole("ROLE_ADMIN"))
                        {
                            <div class="col-4">
                                Bedrijf: <input type="text" class="form-control" name="searchCompany" value="@ViewData["searchCompany"]" />
                            </div>
                        }
                        @if (User.IsInRole("ROLE_EMPLOYER") || User.IsInRole("ROLE_ADMIN"))
                        {
                            <div class="col-4">
                                Naam kandidaat: <input type="text" class="form-control" name="searchCandidate" value="@ViewData["searchCandidate"]" />
                            </div>
                        }
                        <div class="col-4">
                            Uitgenodigd: 
                            <div class="form-input">
                            Ja:<input type="checkbox" name="searchSelectedYes" value="true" checked="@ViewData["searchSelectedYes"]" />
                            </div>
                            <div class="form-input">
                            Nee:<input type="checkbox" name="searchSelectedNo" value="true" checked="@ViewData["searchSelectedNo"]" />
                            </div>
                        </div>
                        <div class="col-3">
                            <input type="submit" value="Filter" class="btn btn-primary" />
                            <a asp-action="index">
                                <input type="button" value="Clear" class="btn btn-primary"/></a>
                        </div>
                    </p>
                    <hr />
                </form>
            </div>
        </div>

        <div class="row">
            <div class="col-2">
            </div>
            <div class="Solicitation-table col-10 d-inline-flex table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.JobOffer.Created)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.JobOffer.Name)
                            </th>
                            @if (User.IsInRole("ROLE_CANDIDATE") || User.IsInRole("ROLE_ADMIN"))
                            {
                                <th>
                                    @Html.DisplayNameFor(model => model.JobOffer.Company.Name)
                                </th>
                            }
                            @if (User.IsInRole("ROLE_EMPLOYER") || User.IsInRole("ROLE_ADMIN"))
                            {
                                <th>
                                    @Html.DisplayNameFor(model => model.User.Name) kandidaat
                                </th>
                            }
                            <th>
                                InterviewAntwoorden
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Selected)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Appointment)
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Date)
                                </td>
                                <td>
                                    <a class="text-decoration-none text-orange" asp-controller="JobOffers" asp-action="Details" asp-route-id="@item.JobOffer.Id">
                                        @if(item.JobOffer.Name.Contains("voor"))
                                        {
                                            var range = item.JobOffer.Name.IndexOf("voor");
                                            @item.JobOffer.Name.Substring(0, range)
                                        } else
                                        {
                                            var range = item.JobOffer.Name.Length;
                                            @item.JobOffer.Name.Substring(0, range)
                                        }
                                    </a>
                                </td>
                                @if (User.IsInRole("ROLE_CANDIDATE") || User.IsInRole("ROLE_ADMIN"))
                                {
                                    <td>
                                        <a class="text-decoration-none text-orange" asp-controller="Companies" asp-action="Details" asp-route-id="@item.JobOffer.Company.Id">
                                            @Html.DisplayFor(modelItem => item.JobOffer.Company.Name)
                                        </a>
                                    </td>
                                }
                                @if (User.IsInRole("ROLE_EMPLOYER") || User.IsInRole("ROLE_ADMIN"))
                                {
                                        <td>
                                            <a class="text-decoration-none text-orange" asp-controller="UserDetails" asp-action="Details" asp-route-id="@item.User.Id">
                                                @Html.DisplayFor(modelItem => item.User.Name)
                                            </a>
                                        </td>
                                }
                                <td>
                                    @if (item.JobOffer.Answers.Any(a => a.UserId == item.UserId))
                                    {
                                        <a class="text-decoration-none text-orange" asp-area="" asp-controller="Answers" asp-action="DetailsPerJobOffer" asp-route-Id="@item.JobOffer.Id" asp-route-userId="@item.UserId">
                                            Antwoorden
                                        </a>
                                    }
                                </td>
                                @if (User.IsInRole("ROLE_CANDIDATE"))
                                {
                                    <td>
                                        @Html.CheckBoxFor(modelItem => item.Selected)
                                    </td>
                                }
                                @if (User.IsInRole("ROLE_EMPLOYER") || User.IsInRole("ROLE_ADMIN"))
                                {
                                    <td>
                                        <a class="text-decoration-none text-orange" asp-action="Select" asp-route-id="@item.Id">
                                            @Html.CheckBoxFor(modelItem => item.Selected)
                                        </a>
                                    </td>
                                }
                                <td>
                                    @if (item.Appointment == null && User.IsInRole("ROLE_CANDIDATE") && item.Selected == true)
                                    {
                                        <a class="text-decoration-none text-orange" asp-controller="Appointments" asp-action="Select" asp-route-id="@item.Id">
                                            Afspraak plannen
                                        </a>
                                    } else
                                    {
                                        if (item.Appointment != null)
                                        {
                                            <a class="text-decoration-none text-orange" asp-controller="Appointments" asp-action="Details" asp-route-id="@item.Appointment.Id">
                                               @Html.DisplayFor(modelItem => item.Appointment.Date) 
                                               @Html.DisplayFor(modelItem => item.Appointment.Time)
                                            </a>
                                        } else
                                        {
                                            @Html.DisplayFor(modelItem => item.Appointment)
                                        }
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}